<!DOCTYPE html>
<html lang="en">
    <head>
        <title>manejo de errores</title>
    </head>
    <body>
        <script>
            // PROMESAS
            function sumarNumeros(a, b) {
            return new Promise(function (resolve, reject) {
                setTimeout(function () {
                if (typeof a !== 'number' || typeof b !== 'number') {
                    reject(new Error("Ambos argumentos deben ser n√∫meros"));
                } else {
                    resolve(a + b);
                }
                }, 1000);
            });
            }

            // Uso de la promesa
            sumarNumeros(1, '2')
            .then(function (resultado) {
                console.log('Resultado:', resultado);
            })
            .catch(function (error) {
                console.error('Error:', error.message);
            });

        </script>
    </body>
</html>